### ISSUE TITLE
想问一下你下拉刷新的方案

### ISSUE THREAD

**Issue by nearxu** [fengyinchao/vue-cnode#1]
列表数据一般是10条，下拉ajax请求listData.concat(data),有什么不需要插件的方式没？

**Comment by nearxu** [comment]
if(scrollTop+windowHeight>documentHeight-2000) 这个2000是那来的？

**Comment by fengyinchao** [comment]
@nearxu 
1、2000是自己定义的，你可以设为其他值
2、不叫下拉吧，应该是上拉，上拉加载更多数据，没有使用插件，只是将新拉来的数据push到原数组中
