### ISSUE TITLE
token

### ISSUE THREAD

**Issue by nearxu** [fengyinchao/vue-cnode#3]
亲测，输入token提示token有误，可是我的token没问题。

**Comment by fengyinchao** [comment]
@nearxu 你把你的token发我试试，我的token是没问题的，我的token是：
cf9f3cff-3972-4e13-8685-9519888563f7

**Comment by nearxu** [comment]
sorry,最近实在太忙没有看到，是我token的问题，一直打扰你万分抱歉。你的代码浅显易懂，写的非常好，希望你继续努力，特别是react这块，共勉。

**Comment by fengyinchao** [comment]
共勉！
